server:
  port: 8081
springdoc:
  swagger-ui:
    path: swagger
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://94.158.219.127:5433/hogwarts
    username: student
    password: chocolatefrog
path:
  to:
    avatars:
      folder: avatar
