server:
  port: 8081
springdoc:
  swagger-ui:
    path: swagger
spring:
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/hogwartslb
    username: student
    password: chocolatefrog
path:
  to:
    avatars:
      folder: avatar
